POST http://localhost:8888/json_api/history
Accept: application/json
Content-Type: application/json

{
  "requestId": "111",
  "timestamp": 1586335186721,
  "client": "1234",
  "currency": "EUR",
  "period": 24
}

###
