POST http://localhost:8888/json_api/current
Accept: application/json
Content-Type: application/json

{
  "requestId": "b89577fe-8c37-bc21",
  "timestamp": "1586335186721",
  "client": "1234",
  "currency": "EUR"
}

###
